# Generated by Django 4.1.4 on 2023-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_postcommentmodel_user_postmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
