# Generated by Django 4.1.4 on 2023-01-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0003_alter_userprofile_user'),
        ('homeApp', '0003_alter_postmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimagesmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homeApp.postmodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to='accountApp.userprofile'),
        ),
    ]
