# Generated by Django 4.1.4 on 2023-01-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0003_alter_favoritecateogrymodel_category'),
        ('homeApp', '0006_postmodel_dateadded_alter_postcommentmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='searchApp.categoriesmodel'),
            preserve_default=False,
        ),
    ]
