# Generated by Django 4.1.4 on 2023-01-08 18:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0008_saveduserposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimagesmodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='postImages/'),
        ),
    ]
