# Generated by Django 4.1.4 on 2023-01-08 18:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0004_userprofile_backgroundimage_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='userImage/'),
        ),
    ]
